# Generated by Django 3.1.1 on 2021-02-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='article.department')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=50000)),
                ('author', models.ManyToManyField(related_name='wrote', to='article.Person')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.department')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited', to='article.person')),
            ],
        ),
    ]
