# Generated by Django 3.1.1 on 2021-02-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210207_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='article.department'),
        ),
    ]
